# Generated by Django 3.2.16 on 2024-07-23 19:24

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20240722_1739'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('published_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
